name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up working directory and run Make commands
        run: |
          cd $GITHUB_WORKSPACE/app
          chmod +x ./gradlew  # Добавляем разрешения на выполнение
          make setup
          make clean
          make build
          make install
          lint build
        
      - uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
