name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '20' #
          distribution: 'temurin'

      - name: Set up working directory
          run: cd $GITHUB_WORKSPACE/app && pwd && ls -la

      - name: Gradle build
        run: |
          ./gradlew wrapper --gradle-version 8.3
          ./gradlew clean build --stacktrace
      
      - name: Run Make commands
        run: |
          make setup
          make clean
          make build
          make install
          lint build
